### ISSUE TITLE
Refactor contact model

### ISSUE THREAD

**Issue by Yehezkiel01** [AY1920S1-CS2103T-F12-3/main#18]
- [x] Refactor person to contact #66 
- [x] Delegate some responsibilities from ModelManager to ContactManager #70
- [x] Add unique ID to contact model #69 
- [x] Update EditCommand and DeleteCommand from using Index to Id #71
- [x] Add test case for ID
