### ISSUE TITLE
As a user I want to view all notes related to a contact

### ISSUE THREAD

**Issue by Yehezkiel01** [AY1920S1-CS2103T-F12-3/main#59]
So that I can discuss these notes with them when I meet them

Break down the task into following subtasks:
- [x] Add Contact Tag #91 
- [x] Filter by tag #92 
- [x] Create `contact show` command  #157
